#!/bin/sh
#
# File:    makeGeodesicCycleLengthDistriubutionTables.sh
# Author:  Alex Stivala
# Created: December 2022
#
# Usage: makeGeodesicCycleLengthDistriubutionTables.sh inputdir
#
#    inputdir is directory containing simualted networks
#
# Output is to stdout.
#
#  e.g.: makeGeodesicCycleLengthDistriubutionTables.sh simulated/model1 > model1_geodesiccycledisttable.txt
#

CYPATHDIR=${HOME}/CYPATH
SCRIPTDIR=`dirname "$0"`
PATH=${SCRIPTDIR}:${PATH}:${CYPATHDIR}

if [ $# -ne 1 ]; then
    echo "Usage: $0 inputdir" >&2
    exit 1
fi
inputdir=$1

echo "# Generated by: $0 $*"
echo "# At: " `date`
echo "# On: " `uname -a`

echo "sim length count" # header line: simulated network num, cycle len, count
for edgelistfile in ${inputdir}/sim_model*_*_edgelist.txt
do
    tmpfile=`mktemp`

    # format of each input edgelist file is e.g. sim_model1_95_edgelist.txt
    # so get number from filename
    num=`echo "${edgelistfile}" | sed 's/.*sim_mode[a-z]*[0-9]*_\([0-9]*\)_edgelist[.]txt/\1/g'`

    # convert to format for CYPATH in tmpfile
    transgrh.pl < ${edgelistfile} > ${tmpfile}
    
    ## run CYPATH and filterCyclesGeodesic.py to get geodesic cycles and
    ## use  uses awk, sort, and uniq to get counts of each geodesic cycle length
    ## Note capital C on cypath to get chordless cycles only,
    ## since a geodesic cycle must be chordless. The "-, ," option sets the
    ## output delimiter to comma, and fgrep used to get only lines with comma,
    ## so that summary (cycle length counts) information is removed (there is 
    ## a q option documented to do this, but appears not to be implemented).
    ##
    output=`cypath C -, , ${tmpfile} - | fgrep , | filterCyclesGeodesic.py  ${edgelistfile}  | awk -F, '{print NF}' | sort -n | uniq -c | awk -vnum=$num '{print num, $2,$1}'`
    if [ -z "$output" ]; then
        # if no geodesic cycles found, then put NA for count and len for this sim
        echo "${num} NA NA"
     else
        echo "${output}"
    fi
    rm ${tmpfile}
done
