#!/bin/sh
#
# File:    makeLongestISometricCycleLengthTables.sh
# Author:  Alex Stivala
# Created: March 2023
#
# Usage: makeLongestISometricCycleLengthTables.sh inputdir
#
#    inputdir is directory containing simualted networks
#
# Output is to stdout.
#
#  e.g.: makeLongestISometricCycleLengthTables.sh simulated/model1 > model1_geodesiccycledisttable.txt
#

SCRIPTDIR=`dirname "$0"`
PATH=${SCRIPTDIR}:${PATH}

if [ $# -ne 1 ]; then
    echo "Usage: $0 inputdir" >&2
    exit 1
fi
inputdir=$1

echo "# Generated by: $0 $*"
echo "# At: " `date`
echo "# On: " `uname -a`

echo "sim maxlen" # header line: simulated network num, longest cycle len
for edgelistfile in ${inputdir}/sim_model*_*_edgelist.txt
do
    tmpfile=`mktemp`

    # format of each input edgelist file is e.g. sim_model1_95_edgelist.txt
    # so get number from filename
    num=`echo "${edgelistfile}" | sed 's/.*sim_mode[a-z]*[0-9]*_\([0-9]*\)_edgelist[.]txt/\1/g'`

    output=`longestIsometricCycle.py -v ${edgelistfile}`
    if [ -z "$output" ]; then
        # if no geodesic cycles found, then put NA for len for this sim
        echo "${num} NA"
     else
        echo "${num} ${output}"
    fi
    rm ${tmpfile}
done
