#!/bin/sh
#
# File:    makeSingleNetworkAtomicCycleLengthDistriubutionTables.sh
# Author:  Alex Stivala
# Created: August 2019
#
# Run the findAtomicCycles program to make tables of atomic cycle
# length distributions from a single network
# for reading in R and plotting etc.
#
# Runs the findAtomicCycles program which uses the
# Waffles machine learning library:
#
# http://gashler.com/mike/waffles/index.html
# https://github.com/mikegashler/waffles
# 
# References:
# 
# Gashler, M. (2011). Waffles: A machine learning toolkit. Journal of
# Machine Learning Research, 12(Jul), 2383-2387.
# 
# Gashler, M., & Martinez, T. (2012). Robust manifold learning with
# CycleCut. Connection Science, 24(1), 57-69.
#
#
# Usage: makeAtomicCycleLengthDistriubutionTables.sh edgelist.txt
#
#    edgelist.txt is edge list fo network 
#
# Output is to stdout.
#
#  e.g.: makeSingleNetworkAtomicCycleLengthDistributionTable.sh patricia90_edgelist.txt > patricia90_atomiccycledisttable.txt
#

FINDATOMICDIR=../../findAtomicCycles/src
PATH=${PATH}:${FINDATOMICDIR}

if [ $# -ne 1 ]; then
    echo "Usage: $0 edgelistfile" >&2
    exit 1
fi
edgelistfile=$1

echo "# Generated by: $0 $*"
echo "# At: " `date`
echo "# On: " `uname -a`

# need number of nodes, just get max node number (and add one)
maxnodenum=`cat ${edgelistfile} | tr ' ' '\n' | sort -n | tail -n-1`
numnodes=`expr $maxnodenum + 1`

echo "length count" # header line: cycle len, count

# run findAtomicCycles to get atomic cycle length distribution
# each line of output is space delimited list of node numbers
# so by just using awk to print number of fields, sorting and using
# -c on uniq option to count, we get a frequency table. Note that uniq -c
# outputs the frequency first, then the string, so we reverse the output
#fields to get length then count
findAtomicCycles ${numnodes} ${edgelistfile} | awk '{print NF}' | sort -n |uniq -c | awk -vnum=$num '{print $2, $1}'
