#!/usr/bin/Rscript
##
## File:    plotCombinedMaxCycleLengthDistributionsFromTables.R
## Author:  Alex Stivala
## Created: June 2020
##
## Read tables generated by makeCycleLengthDistributinoTables.sh and
## make boxplots for maximum cycle length distrubutions for
## simulated networks with points/line for observed network on same
## plot for comparison, for all dk-series models and and ERGM model on
## the same plot.
##
## Usage: Rscript plotCbominedMaxCycleLengthDistributionFromTables.R description ergmtables_globdktables_glob obs_table.txt output_filename.eps
##
##    description    is text description for labels e.g. "chordless cycle"
##    ergmtables_glob is sh glob for cycle length distributions for ERGM models
##                      as produced e.g. by output of
##                      makeCycleLengthDistributionTables.sh
##                      e.g. "model?_atomiccycledisttable.txt". NOTE that
##                      the "model*_" prefix is required to get the ERGM
##                      label.
##    dktables_glob  is shell glob for dk-series tables each of which is
##                      output of e.g. makeCycleLengthDistributionTables.sh.
##                      e.g. "dk*_atomiccycledisttable.txt" NOTE that
##                      the "dk*_" prefix is required to get the dk-series
##                      label e.g. dk21
##    obs_table.txt is cycle length distribution of observed network as e.g.
##                     output of
##                     makeSingleNetworkCycleLengthDistributionTable.sh
##    output_Filename.eps is output EPS filename.
##                         WARNING: output files are overwritten
##
## Example:
##   Rscript ../../scripts/plotCombinedMaxCycleLengthDistributionsFromTables.R 'geodsic cycle' model1_atomiccycledisttable.txt "dk*_atomiccycledisttable.txt" patricia1990_atomiccycletable.txt patricia1990_combined_max_geodesic.eps
##
##


library(ggplot2)
library(doBy)

###
### Main
###
args <- commandArgs(trailingOnly=TRUE)
if (length(args) != 5) {
  cat("Usage: Rscript plotCombinedMaxCycleLengthDistributionsFromTables.R descr ergmtables_globdktables_glob obs_table.txt output.eps\n")
  quit(save="no")
}
descr              <- args[1]
ergmtables_glob    <- args[2]
dk_table_glob      <- args[3]
obs_tablefilename  <- args[4]
outputepsfilename  <- args[5]


obscolour <- 'red' # colour to plot observed graph points/lines
## simulated graph statistics will be boxplot on same plot in default colour

ptheme <-  theme(legend.position = 'none')


obs_dat <- read.table(obs_tablefilename, header=TRUE)

ergm_files <- Sys.glob(ergmtables_glob)
if (length(ergm_files) == 0) {
  cat('No ERGM data\n')
  ergm_dat <- data.frame()
} else {
  cat('Reading ERGM data from ', ergm_files, '\n')
  ergm_dat <- data.frame()
  for (ergmfile in ergm_files) {
    if (length(ergm_files) == 1) {
      ergmname <- 'ERGM'
    } else {
      ergmname <- sub("model([0-9]+)_.+", "ERGM \\1", basename(ergmfile))
    }
    print(ergmname)
    ergmtab <- read.table(ergmfile, header=TRUE)
    ergmtab$method = ergmname
    ergm_dat <- rbind(ergm_dat, ergmtab)
  }
}



dk_files <- Sys.glob(dk_table_glob)
cat('Reading dk-series data from ',dk_files,'\n')
dat <- ergm_dat
for (dkfile in dk_files) {
  dkname <- sub("(dk[0-9]+)_.+", "\\1", basename(dkfile))
  print(dkname)
  if (dkname == "dk0") {
    dkname <- "dk 0 k"
  } else if (dkname == "dk1") {
    dkname <- "dk 1 k"
  } else if (dkname == "dk2") {
    dkname <- "dk 2 k"
  } else if (dkname == "dk21") {
    dkname <- "dk 2.1 k"
  } else if (dkname == "dk25") {
    dkname <- "dk 2.5 k"
  }

  dktab <- read.table(dkfile, header=TRUE)
  dktab$method <- dkname
  dat <- rbind(dat, dktab)
}

dat$method <- factor(dat$method)

obs_maxlen <- max(obs_dat$length)
maxlen <- max(dat$length, obs_maxlen, na.rm=TRUE)
cat('max sim len = ', max(dat$length, na.rm=TRUE), '\n')
cat('max obs len = ', obs_maxlen, '\n')
cat('maxlen = ', maxlen, '\n')

lendf <- dat
maxlendf <- summaryBy(length ~ sim + method , data = lendf, FUN=max)
# replace NA max length with 0 for simulatd newtorks with no cycles
if (any(is.na(maxlendf$length.max))) {
    maxlendf[which(is.na(maxlendf$length.max)),]$length.max <- 0
}
print(length(maxlendf$length.max))
print(summary(maxlendf$length.max))

p <- ggplot(maxlendf, aes(x = method, y = length.max))
p <- p + geom_boxplot()
p <- p + ptheme
p <- p + theme(axis.text = element_text(size = 12))
p <- p + theme(axis.title = element_text(size = 12))
p <- p + ylim(0, maxlen)
p <- p + theme(axis.text.x = element_text(colour = 'black'))
p <- p + ptheme + xlab('Simulation method') + ylab(paste('Length of largest', descr))
p <- p + geom_hline(aes(yintercept = obs_maxlen, colour = obscolour),linetype=2)

cat('Writing to ', outputepsfilename, '\n')
postscript(outputepsfilename, onefile=FALSE, paper="special", width=9, height=6)
print(p)
dev.off()


