#!/usr/bin/Rscript
##
## File:    plotCycleLengthDistributionsFromTables.R
## Author:  Alex Stivala
## Created: July 2019
##
## Read tables generated by makeCycleLengthDistributinoTables.sh
## and make boxplots for simulated networks with points/line for
## observed network on same plot for comparison.
##
## Usage: Rscript plotCycleLengthDistributionFromTables.R description table.txt obs_table.txt
##
##    title       is text for plto title e.g. "ERGM" or "dk-series 2.5 k"
##    description is text description for labels e.g. "chordless cycle"
##    table.txt is output of makeCycleLengthDistributionTables.sh
##    obs_table.txt is output of makeSingleNetworkCycleLengthDistributionTable.sh
##   
##  output files are built from basename of table.txt file as:
##        <tablename>_lengthdist.eps
##        <tablename>_largest.eps
##
##  WARNING: output files are overwritten
##
## Example:
##      Rscript plotEsimtNetDirectedSimFit.R "ERGM" "chordless cycle" model1_chordlesscycledisttable.txt patricia1990_chordlesscycletable.txt
##
##


library(ggplot2)
library(doBy)

###
### Main
###
args <- commandArgs(trailingOnly=TRUE)
if (length(args) != 4) {
  cat("Usage: Rscript plotCycleLengthDistributionsFromTables.R title descr table.txt obs_table.txt\n")
  quit(save="no")
}
title <- args[1]
descr <- args[2]
tablefilename <- args[3]
obs_tablefilename <- args[4]

tablename <- sub("(.+)[.].+", "\\1", basename(tablefilename))

obscolour <- 'red' # colour to plot observed graph points/lines
## simulated graph statistics will be boxplot on same plot in default colour

ptheme <-  theme(legend.position = 'none')

dat <- read.table(tablefilename, header=TRUE)
obs_dat <- read.table(obs_tablefilename, header=TRUE)

## because CYPATH output for each network only has counts up to
## the longest cycle, but different simulated newtorks can have different
## length of longest cycles, we need to pad out entires for each simulated
## network with 0 counts from 1 more than the largest cycle in that network
## up to the largest cycle of any of the networks.
## More genernaly, findAtomicCycles only outputs actual cycles, and so
## the script makeAtomicCycleLengthDistributionTables.sh only has
## entries for cycles that occur (have frequency > 0). 
## So instead of just padding on end, we need to actually add 0 count
## rows for every length that does not occur in the data for each simulated
## network.
## There is probably an easier/better way of doing this without a loop in R
## but this works.
obs_maxlen <- max(obs_dat$length)
maxlen <- max(dat$length, obs_maxlen, na.rm=TRUE)
cat('max sim len = ', max(dat$length, na.rm=TRUE), '\n')
cat('max obs len = ', obs_maxlen, '\n')
cat('maxlen = ', maxlen, '\n')

datf <-data.frame()
for (i in unique(dat$sim)) {
  simi <- dat[which(dat$sim == i),]
  simi <- simi[which(!is.na(simi$length)),]
  stopifnot(length(simi$length) == length(unique(simi$length)))
  if (length(simi$length) < maxlen) {
    for (len in 1:maxlen) {
      if (sum(simi$length == len) == 0) {
        datf <- rbind(datf, data.frame(sim = i, length = len, count = 0))
      } else {
        datf <- rbind(datf, simi[which(simi$length == len),])
      }
    }
  } else {
    datf <- rbind(datf, simi)
  }
}


obs_datf <- data.frame()
stopifnot(length(obs_dat$length) == length(unique(obs_dat$length)))
if (length(obs_dat$length) < maxlen) {
  for (len in 1:maxlen) {
    if (sum(obs_dat$length == len) == 0) {
      obs_datf <- rbind(obs_datf, data.frame(length = len, count = 0))
    } else {
      obs_datf <- rbind(obs_datf, obs_dat[which(obs_dat$length == len),])
    }
  }
} else {
  obs_datf <- obs_dat
}


## remove entries where length <=2 as never cycles of length 1 or 2
stopifnot(sum(datf[which(datf$length <= 2),'count']) == 0)
stopifnot(sum(obs_datf[which(obs_datf$length <= 2),'count']) == 0)
datf <- datf[which(datf$length > 2),]
obs_datf <- obs_datf[which(obs_datf$length > 2),]

datf$length <- as.factor(datf$length)
obs_datf$length <- as.factor(obs_datf$length)


p <- ggplot(datf, aes(x = length, y = count))
p <- p + geom_boxplot()
p <- p + ggtitle(title)
p <- p + xlab(paste('Length of', descr))
p <- p + ptheme + ylab('Count')
p <- p + theme(axis.text = element_text(size = 20))
p <- p + theme(axis.title = element_text(size = 20))
p <- p + theme(plot.title = element_text(size = 20))
p <- p + geom_line(data=obs_datf, aes(x = length, y = count, group=1), 
                                      colour = obscolour)
p <- p + geom_point(data=obs_datf, aes(x = length, y = count, group=1), 
                                      colour = obscolour,shape=23,size=4)

outputepsfilename <- paste(tablename, '_lengthdist.eps', sep='')
cat('Writing to ', outputepsfilename, '\n')
postscript(outputepsfilename, onefile=FALSE, paper="special", width=9, height=6)
print(p)
dev.off()

lendf <- dat
maxlendf <- summaryBy(length ~ sim, lendf, FUN=max)
# replace NA max length with 0 for simulatd newtorks with no cycles
if (any(is.na(maxlendf$length.max))) {
    maxlendf[which(is.na(maxlendf$length.max)),]$length.max <- 0
}
print(length(maxlendf$length.max))
print(summary(maxlendf$length.max))
xfact <- factor(paste('Max', descr, 'length'))
p <- ggplot(maxlendf, aes(x = xfact, y = length.max))
p <- p + geom_boxplot()
p <- p + ggtitle(title)
p <- p + ylim(0, maxlen)
p <- p + theme(axis.title.x = element_blank())
p <- p + theme(axis.text = element_text(size = 20))
p <- p + theme(axis.title = element_text(size = 20))
p <- p + theme(plot.title = element_text(size = 20))
p <- p + ptheme + ylab(paste('Length of', descr))
p <- p + geom_point(aes(x = xfact, y = obs_maxlen), colour = obscolour, shape = 23, size = 4)

outputepsfilename <- paste(tablename, '_largest.eps', sep='')
cat('Writing to ', outputepsfilename, '\n')
postscript(outputepsfilename, onefile=FALSE, paper="special", width=9, height=6)
print(p)
dev.off()


