#!/usr/bin/Rscript
##
## File:    plotCycleLengthDistributionSimFit.R
## Author:  Alex Stivala
## Created: July 2019
##
## Read statnet model and associated network (written by e.g.
## patricia1992/statnetEstimatePatricia1992Model1.R), simulate networks
## from the model, and plot boxplot of simulated network cycle length
## distributions as well as empirical distiribution from the original network
## on same plot.
##
## Usage: Rscript plotEsimtNetDirectedSimFit.R model.RData outfileprefix
##
##    model.RData is R save file with network and model
##    outfileprefix is prefix of output .eps files, model and graph names
##      are appended automatically:
##   
##        outfileprefix_modelname_cycledist.eps
##        outfileprefix_modelname_largestcycle.eps
##
##  WARNING: output files are overwritten
##
## Example:
##      Rscript plotEsimtNetDirectedSimFit.R model1.RData patricia1992_model1_cycledist.eps
##
##
### NOTE: This script no longer needs to be used as it is done much more
### efficiently using plotCycleLengthDistributionsFromTables.R
### using the tables generated by makeCycleLengthDistributionTables.sh
### which reads the simulated networks generated and saved by
### generateSimulatedNetworksFromStatnetModel.R and uses the CPYATH
### program to enumerate [chordless] cycles and is far more efficient than
### using R. Verified that for cycles the new more efficient way generates
### garphs that loko the same as those generated by this script.

library(statnet)
library(ggplot2)
library(parallel)

###
### Main
###

num_cores <- detectCores()
cat('num_cores = ', num_cores)
cl <- makeCluster(num_cores-1)

## need to do this to load packages when using parallel
## https://stackoverflow.com/questions/23096869/calling-functions-from-non-base-r-packages-in-parallel-package-without-library
clusterEvalQ(cl, library(statnet))

args <- commandArgs(trailingOnly=TRUE)
if (length(args) != 2) {
  cat("Usage: Rscript plotCycleLengthDistributionSimFit.R model.RData outfilesprefix\n")
  quit(save="no")
}
modelfilename <- args[1]
outfileprefix <- args[2]

## note we assume the model is the filename e.g. model1.RData contains
## model1 as the statnet model object and the network as gn
modelname <- sub("(.+)[.].+", "\\1", basename(modelfilename))
load(modelfilename)
model <- eval(parse(text = modelname))

summary(gn)
summary(model)

obscolour <- 'red' # colour to plot observed graph points/lines
## simulated graph statistics will be boxplot on same plot in default colour

ptheme <-  theme(legend.position = 'none')

##
## generate simulated networks from model
##
num_sim <- 100
cat("simulating ", num_sim, " newtorks from model...")
system.time( gsim_list <- simulate(model, nsim=num_sim) )

##
## (undirected) cycle length distributions
##
system.time( obs_cyclelens <- kcycle.census(gn, maxlen=network.size(gn),
                                   mode='graph', tabulate.by.vertex=F,
                                   cycle.comembership="none")$cycle.count )

## using parLapplyLB as the time taken for different networks can
## vary greatly (outliers with much larger cycles)
system.time( sim_cyclelens <- parLapplyLB(cl, gsim_list, function(x)
                                   kcycle.census(x, maxlen=network.size(x),
                                   mode='graph', tabulate.by.vertex=F,
                                   cycle.comembership="none")$cycle.count) )
##system.time( sim_cyclelens <- lapply(gsim_list, function(x)
##                                   kcycle.census(x, maxlen=network.size(x),
##                                   mode='graph', tabulate.by.vertex=F,
##                                   cycle.comembership="none")$cycle.count) )

stopifnot(min(as.numeric(names(obs_cyclelens))) == 2)
stopifnot(all(sapply(sim_cyclelens, function(x) min(as.numeric(names(x))) == 2)))

maxobscyclelen <- max(as.numeric(names(obs_cyclelens)[which(obs_cyclelens > 0)]))
maxsimcyclelen_dist <- sapply(sim_cyclelens, function(x)
                                       max(as.numeric(names(x)[which(x > 0)])))
print(maxsimcyclelen_dist)#XXX
maxsimcyclelen <- max(maxsimcyclelen_dist)

maxcyclelen <- max(maxobscyclelen, maxsimcyclelen)
cat("Max obs cycle length is ", maxobscyclelen, "\n")
cat("Max sim cycle length is ", maxsimcyclelen, "\n")
cat("Max cycle length is ", maxcyclelen, "\n")
cyclelen_df <- data.frame(sim = rep(1:num_sim, each = maxcyclelen-1),
                              cyclelen = rep(2:maxcyclelen, num_sim),
                              count = NA)
start = Sys.time()
for (i in 1:num_sim) {
      sg <- sim_cyclelens[[i]]
      cyclelen_df[which(cyclelen_df[,"sim"] == i), "count"] <- sg[1:(maxcyclelen-1)]
}
cyclelen_df$cyclelen <- factor(cyclelen_df$cyclelen, levels=2:maxcyclelen)
cyclelen_df$frequency <- cyclelen_df$count
end = Sys.time()
cat("Cycle length sim data frame construction took",
        as.numeric(difftime(end, start, unit="secs")), "s\n")
start = Sys.time()
obs_cyclelen_df <- data.frame(cyclelen = 2:maxcyclelen,
                          count = as.numeric(obs_cyclelens[1:(maxcyclelen-1)]))
obs_cyclelen_df$frequency <- obs_cyclelen_df$count
obs_cyclelen_df$cyclelen = as.factor(obs_cyclelen_df$cyclelen)
end = Sys.time()
cat("Cycle length obs data frame construction took",
        as.numeric(difftime(end, start, unit="secs")), "s\n")
print(obs_cyclelen_df)#XXX
print(cyclelen_df)#XXX
p <- ggplot(cyclelen_df, aes(x = cyclelen, y = frequency)) + geom_boxplot()
p <- p + geom_line(data = obs_cyclelen_df, aes(x = cyclelen, y = frequency,
                                             colour = obscolour, group = 1))
p <- p + ptheme + xlab("cycle length") + ylab("frequency")


outputepsfilename <- paste(outfileprefix,'_',modelname,'_cycledist.eps',sep='')
cat("writing plot to EPS file ", outputepsfilename, "\n")
postscript(outputepsfilename, onefile=FALSE, paper="special", width=9, height=6)
print(p)
dev.off()

###
### write plot of max cycle length, boxplot of simulated, point for observed
###
outputepsfilename <- paste(outfileprefix,'_',modelname,'_largestcycle.eps',
                            sep='')
cat("writing plot to EPS file ", outputepsfilename, "\n")
postscript(outputepsfilename, onefile=FALSE, paper="special", width=9, height=6)
p <- ggplot() + geom_boxplot(aes(x = factor('Max cycle length'),
                                 y = maxsimcyclelen_dist))
p <- p + geom_point(aes(x = as.numeric(factor('Max cycle length')),
                        y = maxobscyclelen, colour = obscolour))
p <- p + ptheme + ylab('length of cycle')
p <- p + theme(axis.title.x = element_blank())
print(p)
dev.off()

stopCluster(cl)


