#!/bin/sh
#
# File:    statnetEstimation2textable.sh
# Author:  Alex Stivala
# Created: January 2014
#
# Updated February 2023 for ergm 4.3.2 output format.
#
# Read last estimation result from a Statnet MLE
# estimation output file and convert to LaTeX table.
#
# Usage: statnetEstimation2textable.sh   estimation_output_file.txt
#
# E.g.:
#   statnetEstimation2textable.sh.sh  statnet_estimation_gof_netscience.txt
#
# Output is to stdout
#
# Uses various GNU utils options on echo, etc.

if [ $# -ne 1 ]; then
    echo "usage: $0 estimation_file.txt" >&2
    exit 1
fi

estimationresults=$1

tmpfile=`mktemp`

echo "% Generated by: $0 $*"
echo "% At: " `date`
echo "% On: " `uname -a`

# get line number of start of last Estimation result
lineno=`grep -n 'Results:' $estimationresults | cut -d: -f1 | tail -1`
# there is now a blank line after ... Results line so add 1
lineno=`expr $lineno + 1`
# write last estimation results to tmpfile (start at line no, end on '---'),
# also convert scientific notation to latex format and sort
awk -vlineno=$lineno 'NR > lineno+1' $estimationresults | sed -n '0,/^---/p' | head -n-1 | sed 's/_/\\_/g' | sed 's/< \([0][.][0-9]*\)/<\1/g' | sed 's/< *\([0-9]*\)e[-]\([0-9]*\)/<\1\\times10\^{-\2}/g'  | sort -k1,1 >  $tmpfile

# also write AIC and BIC, parsed from e.g.:
# AIC: 90.61    BIC: 98.14    (Smaller is better.)
aic=`grep -w AIC ${estimationresults} | awk '{print $2}'`
bic=`grep -w AIC ${estimationresults} | awk '{print $4}'`


#format into LaTeX table with 4 digits on floating point numbers

echo '\begin{tabular}{lrrrl}'
echo '\hline'  
echo 'Effect & Estimate & std. error & p-value & \\'
echo '\hline'  
awk '{printf("%s & $%.4f$ & $%.4f$ & $%s$ &  %s \\\\\n",$1,$2,$3,$6,$7)}' $tmpfile
echo '\hline'
# printf 'AIC & $%.2f$ &  &  &   \\\\\n' ${aic}
# printf 'BIC & $%.2f$ &  &  &   \\\\\n' ${bic}
# echo '\hline'  
echo '\end{tabular}'


rm $tmpfile
