#!/bin/sh
#
# File:    statnetEstimation2textable.sh
# Author:  Alex Stivala
# Created: January 2014
#
# Read last estimation result from a Statnet MLE
# estimation output file and convert to LaTeX table.
#
# Usage: statnetEstimation2textable.sh   estimation_output_file.txt
#
# E.g.:
#   statnetEstimation2textable.sh.sh  statnet_estimation_gof_netscience.txt
#
# Output is to stdout
#
# Uses various GNU utils options on echo, etc.

if [ $# -ne 1 ]; then
    echo "usage: $0 estimation_file.txt" >&2
    exit 1
fi

estimationresults=$1

tmpfile=`mktemp`

echo "% Generated by: $0 $*"
echo "% At: " `date`
echo "% On: " `uname -a`

# get line number of start of last Estimation result
lineno=`grep -n 'MLE Results:' $estimationresults | cut -d: -f1 | tail -1`

# write last estimation results to tmpfile (start at line no, end on '---'),
# alos convert PNet effect names into same as used in Snowball PNet and sort
awk -vlineno=$lineno 'NR > lineno+1' $estimationresults | sed -n '0,/^---/p' | head -n-1 |  sed 's/edges/Edge/;s/altkstar/K-Star(2.00)/;s/gwdsp.fixed.0.693[0-9]*/A2P-T(2.00)~\\small{[gwdsp(ln(2))]}/;s/gwesp.fixed.0.693[0-9]*/AKT-T(2.00)~\\small{[gwesp(ln(2))]}/' | sed 's/_/\\_/g' | sed 's/< \([0][.][0-9]*\)/<\1/g' | sed 's/< *\([0-9]*\)e[-]\([0-9]*\)/<\1\\times10\^{-\2}/g'  | sort -k1,1 >  $tmpfile




#format into LaTeX table with 4 digits on floating point numbers

echo '\begin{tabular}{lrrrl}'
echo '\hline'  
echo 'Effect & Estimate & std. errror & p-value & \\'
echo '\hline'  
awk '{printf("%s & $%.4f$ & $%.4f$ & $%s$ &  %s \\\\\n",$1,$2,$3,$5,$6)}' $tmpfile
echo '\hline'  
echo '\end{tabular}'


rm $tmpfile
